### PR TITLE
Mutable store

### PR DESCRIPTION
**Pull request by mjhm**
@sporto Here's my promised PR for https://github.com/Versent/redux-crud/issues/7.  I still owe a bunch of tests, but I wanted to get it to you before fleshing them out.  Most of the new files are copies and minor modifications to the "example" files.

Note that although the "mutable store" is just using arrays and objects, it's still being managed with immutable operations.  In particular the records array is always replaced instead of mutated.

The config for this is currently `{ mutable: true }`.  I debated with myself about using `{ immutable: false }` instead.  The advantage to the latter is that it leaves open the possibility of doing something like `{ immutable: 'immutablejs' }` in case someone wanted to implement the reducers with `immutablejs` instead.  The disadvantages are that `{ immutable: false }` is a confusing double negative, and it would require adding `immutable: true` to the configs in all of the existing unit tests.  Any strong feelings one way or another?

I also implemented utility methods onto the records arrays: `.get` and `.getIndex`.  These allow hash lookups by the id key of the records.  I figured that as long as we're requiring unique keys in the records, we might as well take advantage of them.

### CODE REVIEW

**Comment by sporto** [comment]
Hi @mjhm this is looking good, a couple of things:

__Re mutable: true__

As you said we might end up adding immutablejs at some point, so I think we need something in the config like:

```
store: 'mutable'
```

instead of `mutable: true`, later we could have `store: 'immutablejs`.

__Re ensureGetters__

I'm not keen on adding those 'get' functions to arrays. Could you just have some utility functions that receive an array an do what you need?  So:

```
getIndex(current, deleteId);
```

instead of

```
current.getIndex(deleteId);
```

I just think that the functional approach is more flexible.

**Comment by mjhm** [comment]
Thanks -- both good suggestions.  In particular attaching extra stuff to a standard object (Array) would be offensive to a lot of people.  I'll pull it out and perhaps create a separate issue to implement some kind of hash lookup for the records if I find I'm needing it.

**Comment by sporto** [comment]
@mjhm I would like to ask you something more:

For the store configuration please add a constant, so users can do:

```
reduxCrud.STORE_MUTABLE
```

So in `index.js` export `STORE_MUTABLE` inside the exports block.

Then store config would be:

```
store: reduxCrud.STORE_MUTABLE
```

This is more verbose than `store: 'mutable'` but safer in the long run.

**Comment by mjhm** [comment]
I like that idea as well.  However I'm having trouble referencing the top level `index.js` file from `lib/reducers/common.js`.  It looks like its not liking a circular require reference in the tests.  So I'm creating a `constants.js` file at the top level and importing it into `index.js` and merging the constants for the same effect.  What do you think of creating a `{ DEFAULT_KEY: 'id' }` constant as well?

**Comment by sporto** [comment]
@mjhm having a constants.js sounds like the best way to go. Agree `DEFAULT_KEY` would be great.

**Comment by mjhm** [comment]
@sporto This wraps up everything I think.  Let me know if there's anything else.  Thanks.

**Comment by sporto** [comment]
Thanks for the PR. Published `v0.9.0` with this change.

**Comment by mjhm** [comment]
:+1: Thank you as well.

**Pull request merged**
